# Generated by Django 4.2.7 on 2023-11-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_tache_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tache',
            name='activite',
        ),
        migrations.RemoveField(
            model_name='tache',
            name='categorie',
        ),
        migrations.AddField(
            model_name='tache',
            name='activite',
            field=models.ManyToManyField(to='project.activite', verbose_name='Activite'),
        ),
        migrations.AddField(
            model_name='tache',
            name='categorie',
            field=models.ManyToManyField(to='project.categorie', verbose_name='Categorie'),
        ),
    ]
