# Generated by Django 4.2.7 on 2023-11-13 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressource', '0007_alter_technicien_photo'),
        ('project', '0003_remove_tache_activite_remove_tache_categorie_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Donnee_jour',
            new_name='DonneeJour',
        ),
        migrations.RemoveField(
            model_name='rapport',
            name='createdAt',
        ),
        migrations.AddField(
            model_name='tache',
            name='assignations',
            field=models.ManyToManyField(through='project.TechnicienTache', to='ressource.technicien'),
        ),
        migrations.AlterField(
            model_name='enregistrementjournalier',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tache',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tache',
            name='date_debut',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='tache',
            name='date_fin',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='tache',
            name='status',
            field=models.CharField(choices=[('En attente', 'En attente'), ('En cours', 'En cours'), ('En arrêt', 'En arrêt'), ('Effectué', 'Effectué')], default='En attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='tache',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
