# Generated by Django 4.2.7 on 2023-11-13 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_rename_donnee_jour_donneejour_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='tache',
        ),
        migrations.AlterUniqueTogether(
            name='donneestechnicien',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='donneestechnicien',
            name='technicien',
        ),
        migrations.DeleteModel(
            name='EnregistrementJournalier',
        ),
        migrations.AlterUniqueTogether(
            name='tacheattribuee',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='tacheattribuee',
            name='tache',
        ),
        migrations.RemoveField(
            model_name='tacheattribuee',
            name='technicien',
        ),
        migrations.RemoveField(
            model_name='tacheeffectuee',
            name='rapport',
        ),
        migrations.RemoveField(
            model_name='tacheeffectuee',
            name='tache',
        ),
        migrations.RemoveField(
            model_name='rapport',
            name='technicien_tache',
        ),
        migrations.AddField(
            model_name='rapport',
            name='tache',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.tache', verbose_name='Tâche effectuée par le technicien'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tache',
            name='activite',
            field=models.ManyToManyField(db_index=True, to='project.activite', verbose_name='Activite'),
        ),
        migrations.AlterField(
            model_name='tache',
            name='categorie',
            field=models.ManyToManyField(db_index=True, to='project.categorie', verbose_name='Categorie'),
        ),
        migrations.AlterField(
            model_name='tache',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='tache',
            name='nom',
            field=models.CharField(db_index=True, max_length=200, verbose_name='intitule'),
        ),
        migrations.AlterField(
            model_name='tache',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='technicientache',
            name='date_debut',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='technicientache',
            name='date_fin',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de fin'),
        ),
        migrations.DeleteModel(
            name='Action',
        ),
        migrations.DeleteModel(
            name='DonneesTechnicien',
        ),
        migrations.DeleteModel(
            name='TacheAttribuee',
        ),
        migrations.DeleteModel(
            name='TacheEffectuee',
        ),
    ]
